[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "earthreach-agent-challenge"
version = "0.1.0"
description = "EarthReach Agent: Dual-LLM Framework for Validated Meteorological Chart Descriptions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "earthkit>=0.10.3",
    "earthkit-data>=0.13.8",
    "earthkit-plots>=0.3.1",
    "openai>=1.77.0",
    "python-dotenv>=1.1.0",
    "hatchling>=1.27.0",
]

[dependency-groups]
dev = [
    "jupytext>=1.17.1",
    "ipykernel>=6.29.5",
]

[tool.hatch.build.targets.wheel]
packages = ["src/earthreach-agent"]